server:
  shutdown: graceful
  port: 8443
  ssl:
    enabled: false

spring:
  profiles:
    active: dev

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
        hbm2ddl:
          auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: scoop


logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

springdoc:
  swagger-ui:
    path: /docs

