services:
  postgres:
    image: postgres:latest
    container_name: scoop-postgres
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: postgres
      TZ: Asia/Seoul
    volumes:
      - .docker-volumes/postgres/data:/var/lib/postgresql/data
      - .docker-volumes/postgres/init:/docker-entrypoint-initdb.d
