name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: build script execute
        run: sudo bash ./build.sh

      - name: Delete file in server
        run: sudo rm -rf /home/ubuntu/scoop-backend

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./ztarget"
          target: "/home/ubuntu/scoop-backend"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/scoop-backend/auth

            sudo docker stop auth || true
            sudo docker rm auth || true
            sudo docker build -t auth .
            sudo docker run -d -p 8080:8080 --name auth

            cd /home/ubuntu/scoop-backend/scoop
            
            sudo docker stop scoop || true
            sudo docker rm scoop || true
            sudo docker build -t scoop .
            sudo docker run -d -p 8081:8081 --name scoop

